// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_1PWclXw5Y09OKnkHYdWMQe8gHgx4R8',
    appId: '1:37312603811:web:0ec15d4b18f664c88ac116',
    messagingSenderId: '37312603811',
    projectId: 'gateguard-65994',
    authDomain: 'gateguard-65994.firebaseapp.com',
    storageBucket: 'gateguard-65994.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgp3poP7q6jA6DzldLeBwQOH12lkLItUM',
    appId: '1:37312603811:android:a16d0bf9daf0490b8ac116',
    messagingSenderId: '37312603811',
    projectId: 'gateguard-65994',
    storageBucket: 'gateguard-65994.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQeesPMqRze23tGAZ3UOj_1wrDjDK0yUk',
    appId: '1:37312603811:ios:330649bae781730b8ac116',
    messagingSenderId: '37312603811',
    projectId: 'gateguard-65994',
    storageBucket: 'gateguard-65994.firebasestorage.app',
    androidClientId: '37312603811-fgq13801npbtdf52d3j3b7gej4l9eba5.apps.googleusercontent.com',
    iosClientId: '37312603811-6fij9b7uhtirejm9329smvgn42cb76o8.apps.googleusercontent.com',
    iosBundleId: 'in.smartdwelliot.gloriaconnect.gloriaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQeesPMqRze23tGAZ3UOj_1wrDjDK0yUk',
    appId: '1:37312603811:ios:330649bae781730b8ac116',
    messagingSenderId: '37312603811',
    projectId: 'gateguard-65994',
    storageBucket: 'gateguard-65994.firebasestorage.app',
    androidClientId: '37312603811-fgq13801npbtdf52d3j3b7gej4l9eba5.apps.googleusercontent.com',
    iosClientId: '37312603811-6fij9b7uhtirejm9329smvgn42cb76o8.apps.googleusercontent.com',
    iosBundleId: 'in.smartdwelliot.gloriaconnect.gloriaConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB18FOCxuV_zKBLJPOBS6vg119SfpVs6eY',
    appId: '1:37312603811:web:c987a610fbde30048ac116',
    messagingSenderId: '37312603811',
    projectId: 'gateguard-65994',
    authDomain: 'gateguard-65994.firebaseapp.com',
    storageBucket: 'gateguard-65994.firebasestorage.app',
  );
}
